workbench_access_taxonomy.settings:
  type: config_object
  label: 'Workbench Access Taxonomy Settings'
  mapping:
    workbench_access_taxonomy:
      type: mapping
      mapping:
        access_control_field:
          type: text
          label: 'Access control field machine name:'
